name: Keep Render Alive

on:
  schedule:
    - cron: "*/14 * * * *"   # every 14 minutes
  workflow_dispatch:          # allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render App
        run: curl -s https://karunasetu.onrender.com > /dev/null
